const { run, get } = require('../../db')

module.exports = function create ({ projectId, sceneId, shotId, at }) {
  // determine the next take number given the shot id
  let { take_number } = get(
    `SELECT COUNT(id) + 1 as take_number FROM takes WHERE shot_id = ?`,
    shotId
  )

  // insert and get the lastInsertRowid for lookup
  let { lastInsertRowid } = run(
    `INSERT INTO takes
    (project_id, scene_id, shot_id,
      take_number,
      ready_at,
      downloaded)
    VALUES
    (?, ?, ?,
      ?,
      ?,
      0
    )`,
    projectId, sceneId, shotId,
    take_number,
    at
  )

  // use the lastInsertRowid to return the id string generated by the insert trigger
  return get(`SELECT id FROM takes WHERE rowid = ?`, lastInsertRowid).id
}
