#!/usr/bin/env bash
# uses:
# /tmp/media/take.mov (from camera take)
# /tmp/media/take.jpg (from camera "screennail")
# /tmp/media/stream.mp4 (from camera rtsp stream)
DEBUG=shotcore:*,rtsp-streaming-server:* \
TAKE_MOV=./tmp/media/take.mov \
npm run zcam-mock-server &
sleep 3
ffmpeg \
  -v warning \
  -re \
  -stream_loop -1 \
  -i tmp/media/stream.mp4 \
  -c:v copy \
  -f rtsp \
  rtsp://127.0.0.1:5554/live_stream
