#!/usr/bin/env bash
echo "Preparing ZIP …"
mkdir -p tmp
pushd test/fixtures/multi-scene > /dev/null
zip -q -r ../../../tmp/multi-scene.zip *
popd > /dev/null
echo "Uploading …"
curl \
  --silent \
  --output /dev/null \
  --show-error \
  --fail \
  -X POST \
  -F "name=multi-part" \
  -F "file=@tmp/multi-scene.zip" \
  "http://localhost:${PORT:-4000}/projects"

echo "Setting an f-stop and Shot Type for Shot 1 …"
curl \
  --silent \
  --output /dev/null \
  --show-error \
  --fail \
  -H "Content-Type: application/json" \
  -X PATCH \
  -d '{ "fStop": "f/5.6"}' \
  "http://localhost:${PORT:-4000}/projects/1/scenes/1/shots/1"

curl \
  --silent \
  --output /dev/null \
  --show-error \
  --fail \
  -H "Content-Type: application/json" \
  -X PATCH \
  -d '{ "shotType": "Medium, Low Angle" }' \
  "http://localhost:${PORT:-4000}/projects/1/scenes/1/shots/1"

echo "Done"
